stages:
    - test
    - doc

image: code.ungleich.ch:5050/ungleich-public/cdist-contrib/ci-container:latest

shellcheck:
    stage: test
    script:
        - make lint

manpages:
    stage: test
    script:
      - make check-manpages

docs:
    stage: doc
    script:
      - make docs
