stages:
    - test

image: code.ungleich.ch:5050/ungleich-public/cdist/cdist-ci:latest

shellcheck:
    stage: test
    script:
        - ./scripts/run-shellcheck.sh

manpages:
    stage: test
    script:
      - ./scripts/run-manpage-checks.sh
